services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    env_file: .env
    ports:
      - "${BACKEND_PORT:-3000}:${BACKEND_PORT:-3000}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT:-3000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "${EXTERNAL_PORT_HTTP:-80}:80"
      - "${EXTERNAL_PORT_HTTPS:-443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    entrypoint: sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h; done"

volumes:
  certbot-etc:
  certbot-var:
