services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    env_file: ./backend/.env
    environment:
      - PORT=3000
    network_mode: "host"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
