import { detectAIContent } from '../src/services/homework.service';
import fs from 'fs';
import path from 'path';

async function run() {
  const modelDir = path.resolve(__dirname, '../data');
  const modelFile = path.join(modelDir, 'homework_model.bin');
  if (!fs.existsSync(modelFile)) {
    fs.mkdirSync(modelDir, { recursive: true });
    const model = {
      weights: { chatgpt: 2.0, ai: 1.5 },
      bias: -1.0,
      threshold: 0.5,
    };
    fs.writeFileSync(modelFile, JSON.stringify(model));
  }

  const human = await detectAIContent('This is a regular homework submission.');
  if (human !== false) {
    throw new Error('Expected false for regular homework text');
  }

  const ai = await detectAIContent('This text was generated by ChatGPT.');
  if (ai !== true) {
    throw new Error('Expected true for AI-generated text');
  }
  console.log('homework.test.ts passed');
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
