name: mrs_unkwn_app
description: Mrs-Unkwn Flutter app
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  local_auth: ^2.1.6

flutter:
  uses-material-design: true
  generate: true
  l10n:
    arb-dir: lib/l10n
    template-arb-file: app_en.arb
    output-localization-file: app_localizations.dart
