name: mrs_unkwn_app
description: Mrs-Unkwn Flutter app

environment:
  # CI hat Dart 3.5.3 -> Constraint so setzen, dass 3.5.x erlaubt ist.
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  local_auth: ^2.1.6
  dio: ^5.3.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  flutter_secure_storage: ^9.0.0
  go_router: ^12.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  web_socket_channel: ^2.4.0
  fl_chart: ^0.66.0
  device_info_plus: ^9.0.2
  battery_plus: ^5.0.1
  disk_space: ^0.2.1

  # Wichtig: aktualisiert, damit das Android/Gradle-Setup (AGP 8.x, compileSdk 35) sauber läuft
  geolocator: ^14.0.2

  encrypt: ^5.0.1
  http: ^1.1.0
  speech_to_text: ^6.3.0
  firebase_core: ^2.25.3
  firebase_crashlytics: ^3.4.5
  firebase_performance: ^0.9.3+12

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  bloc_test: ^9.1.0
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  generate: true
